parserOptions:
  sourceType: "module"
plugins:
  - jsx-a11y
extends:
  - standard-react
  - plugin:jsx-a11y/recommended
rules:
  node/no-unsupported-features/es-syntax: 0
  # node/no-missing-import: 0
  node/no-extraneous-import: 0
  node/no-extraneous-require: 0
  # node/no-unpublished-import: 0
  react/jsx-no-bind: 0
  react/jsx-fragments: 0
  react/jsx-curly-newline: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/no-autofocus: 0
  jsx-quotes:
    - error
    - prefer-single
env:
  node: true # webpack
  browser: true
